version: "3.8"

services:

  backend:
    build: ./Backend
    container_name: project-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - project-network

  frontend:
    build: ./frontend
    container_name: project-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - project-network

  mongo:
    image: mongo:6
    container_name: project-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  mongo-data: